# Project information
site_name: Cyberspace Explore 
use_directory_urls: true

# Repository
# repo_name: Cyberspace-Explore
# repo_url: https://github.com/AvenMay/cyberspace-explore

# Configuration
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/rocket-launch
    # repo: fontawesome/brands/github
  palette:
    - scheme: default    # 浅色模式
      # primary: indigo
      # accent: indigo
      primary: blue
      accent: pink
      toggle:
        icon: material/weather-night
        name: 切换到深色模式
    - scheme: slate      # 深色模式
      # primary: indigo
      # accent: indigo
      primary: blue
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono

  toc:
    on_page: true
    depth: 5


# Page tree
nav:
  - Home: index.md

  # Computer-Science Topic
  - Computer-Science: 
    - computer-science/index.md
    - Programming Languages:
      - computer-science/programming-languages/index.md
      - Compilers:
        - computer-science/programming-languages/compilers/index.md

    - Algorithms & Data-Structures:
      - computer-science/algorithms-data-structures/index.md
      - computer-science/algorithms-data-structures/foundation.md
      - computer-science/algorithms-data-structures/advanced.md
      - computer-science/algorithms-data-structures/problem-solving-techniques.md
    - Computer Architecture:
      - computer-science/computer-architecture/index.md
    - Operating System: 
      - computer-science/operating-system/index.md
      - Unix-like:
        - computer-science/operating-system/unix-and-unix-like/index.md
        - computer-science/operating-system/unix-and-unix-like/linux.md
        - computer-science/operating-system/unix-and-unix-like/bsd.md
        - computer-science/operating-system/unix-and-unix-like/xnu.md
        - computer-science/operating-system/unix-and-unix-like/android.md
      - computer-science/operating-system/windows-nt.md
      - Teaching Purposes:
        - computer-science/operating-system/teaching-purposes/xv6.md
        - computer-science/operating-system/teaching-purposes/pintos.md
        - computer-science/operating-system/teaching-purposes/nachos.md
        - computer-science/operating-system/teaching-purposes/minix3.md
      - Special Use-Cases:
        - computer-science/operating-system/special-use-cases/virtualization.md
        - computer-science/operating-system/special-use-cases/containerization.md
        - computer-science/operating-system/special-use-cases/real-time-os.md
      - computer-science/operating-system/boot-process.md
      - computer-science/operating-system/experimental-os.md

    - Computer Networking:
      - computer-science/computer-networking/index.md
    - Mathematics:
      - computer-science/mathematics/index.md
    - Databases Systems:
      - computer-science/databases-systems/index.md
    - Distributed Systems:
      - computer-science/distributed-systems/index.md
    - Computer Graphics:
      - computer-science/computer-graphics/index.md

  # Software-Engineering Topic
  - Software-Engineering:
    - software-engineering/index.md
    - software-engineering/devops.md
    - Programming Languages:
      - software-engineering/programming-languages/index.md
      - Preparation:
        - software-engineering/programming-languages/preparation/ranking-analysis.md
        - software-engineering/programming-languages/preparation/editor.md
        - software-engineering/programming-languages/preparation/encoding.md
      - Dynamic:
        - software-engineering/programming-languages/dynamic/python.md
        - software-engineering/programming-languages/dynamic/javascript.md
        - software-engineering/programming-languages/dynamic/ruby.md
        - software-engineering/programming-languages/dynamic/php.md
        - software-engineering/programming-languages/dynamic/lua.md
        - software-engineering/programming-languages/dynamic/perl.md
      - Static:
        - software-engineering/programming-languages/static/go.md
        - software-engineering/programming-languages/static/typescript.md
        - software-engineering/programming-languages/static/java.md
        - software-engineering/programming-languages/static/c-sharp.md
        - software-engineering/programming-languages/static/kotlin.md
        - software-engineering/programming-languages/static/swift.md

      - System Level:
        - software-engineering/programming-languages/system-level/c.md
        - software-engineering/programming-languages/system-level/cpp.md
        - software-engineering/programming-languages/system-level/rust.md
        - software-engineering/programming-languages/system-level/assembly.md
      - Functional:
        - software-engineering/programming-languages/functional/haskell.md
        - software-engineering/programming-languages/functional/scala.md
        - software-engineering/programming-languages/functional/ocaml.md
        - software-engineering/programming-languages/functional/elixir.md

    - Development:
      - software-engineering/development/index.md
      - software-engineering/development/vibe-coding.md
      - software-engineering/development/git.md
      - software-engineering/development/cicd.md
      - software-engineering/development/testing.md
    - Operations:
      - software-engineering/operations/index.md
      - Sysadmin:
        - software-engineering/operations/sysadmin/unix-linux.md
        - software-engineering/operations/sysadmin/windows.md
      - software-engineering/operations/sre.md
      - software-engineering/operations/iac.md
      - software-engineering/operations/observability.md
    - Collaboration:
      - software-engineering/collaboration/index.md

  # Computer-Engineering Topic
  - Computer-Engineering:
    - computer-engineering/index.md
    - Electronic-Engineering:
      - electronic-engineering/index.md

  # Internet-System Topic
  - Internet-System: 
    - internet-system/index.md
    - System-Design:
      - internet-system/system-design/index.md
    - Application:
      - internet-system/application/index.md
      - internet-system/application/architecture.md
      - internet-system/application/api-design.md
      - internet-system/application/application-client.md
      - internet-system/application/application-server.md
      - internet-system/application/middleware.md
      - internet-system/application/protocols.md
      - internet-system/application/databases.md
      - internet-system/application/use-cases.md
    - Infrastructure:
      - internet-system/infrastructure/index.md
      - Sysadmin:
        - internet-system/infrastructure/sysadmin/index.md
      - Storage Engineering:
        - internet-system/infrastructure/storage-engineering/index.md
      - Network Engineering:
        - internet-system/infrastructure/network-engineering/index.md
      - Cloud Computing:
        - internet-system/infrastructure/cloud-computing/cloud-providers.md
        - internet-system/infrastructure/cloud-computing/x_aas.md
        - internet-system/infrastructure/cloud-computing/virtualization.md
        - internet-system/infrastructure/cloud-computing/containerization.md
        - internet-system/infrastructure/cloud-computing/networking.md
        - internet-system/infrastructure/cloud-computing/storage.md
      - Mobile Computing:
        - internet-system/infrastructure/mobile-computing/index.md
    - IoT:
        - internet-system/iot/index.md

  # Cybersecurity Topic
  - Cybersecurity:
    - cybersecurity/index.md
    - Cryptography:
      - cybersecurity/cryptography/index.md
    - CTF:
      - cybersecurity/ctf/index.md
    - Security-Skills:
      - cybersecurity/security-skills/index.md
    - Security-Topics:
      - cybersecurity/security-topics/index.md
    - Offensive-Security:
      - cybersecurity/offensive-security/index.md
    - Defensive-Security:
      - cybersecurity/defensive-security/index.md

  # Artificial-Intelligence Topic
  - Artificial-Intelligence:
    - artificial-intelligence/index.md

  # Interesting Topic
  - Interesting-Practice:
    # - interesting-practice/index.md
    - HomeLab:
      - interesting-practice/homelab/index.md
    - CyberDeck:
      - interesting-practice/cyberdeck/index.md

plugins:
  - search
  - macros

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true 

extra:
  files_server: "https://files.cyberspace.bar"
  # files_server: "https://files.cyberspace.bar/cyberspace-explore"

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js 
