# Project information
site_name: Cyberspace Explore 
use_directory_urls: true

# Repository
# repo_name: Cyberspace-Explore
# repo_url: https://github.com/AvenMay/cyberspace-explore

# Configuration
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/rocket-launch
    # repo: fontawesome/brands/github
  palette:
    - scheme: default    # 浅色模式
      # primary: indigo
      # accent: indigo
      primary: blue
      accent: pink
      toggle:
        icon: material/weather-night
        name: 切换到深色模式
    - scheme: slate      # 深色模式
      # primary: indigo
      # accent: indigo
      primary: blue
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono

  toc:
    on_page: true
    depth: 5


# Page tree
nav:
  - Home: index.md

  # Computer-Science Topic
  - Computer-Science: 
    - computer-science/index.md
    - Programming Languages:
      - computer-science/programming-languages/index.md
      - Compilers:
        - computer-science/programming-languages/compilers/index.md

    - Algorithms & Data-Structures:
      - computer-science/algorithms-data-structures/index.md
      - computer-science/algorithms-data-structures/foundation.md
      - computer-science/algorithms-data-structures/advanced.md
      - computer-science/algorithms-data-structures/problem-solving-techniques.md
    - Computer Architecture:
      - computer-science/computer-architecture/index.md
    - Operating System: 
      - computer-science/operating-system/index.md
      - Unix-like:
        - computer-science/operating-system/unix-and-unix-like/index.md
        - computer-science/operating-system/unix-and-unix-like/linux.md
        - computer-science/operating-system/unix-and-unix-like/bsd.md
        - computer-science/operating-system/unix-and-unix-like/xnu.md
        - computer-science/operating-system/unix-and-unix-like/android.md
      - computer-science/operating-system/windows-nt.md
      - Teaching Purposes:
        - computer-science/operating-system/teaching-purposes/xv6.md
        - computer-science/operating-system/teaching-purposes/pintos.md
        - computer-science/operating-system/teaching-purposes/nachos.md
        - computer-science/operating-system/teaching-purposes/minix3.md
      - Special Use-Cases:
        - computer-science/operating-system/special-use-cases/virtualization.md
        - computer-science/operating-system/special-use-cases/containerization.md
        - computer-science/operating-system/special-use-cases/real-time-os.md
      - computer-science/operating-system/boot-process.md
      - computer-science/operating-system/experimental-os.md

    - Computer Networking:
      - computer-science/computer-networking/index.md
    - Mathematics:
      - computer-science/mathematics/index.md
    - Databases Systems:
      - computer-science/databases-systems/index.md
    - Distributed Systems:
      - computer-science/distributed-systems/index.md
    - Computer Graphics:
      - computer-science/computer-graphics/index.md

  # Computer-Engineering Topic
  - Computer-Engineering:
    - computer-engineering/index.md
    - Embedded-System:
      - computer-engineering/embedded-system/index.md
    - 3D-Printing:
      - computer-engineering/3d-printing/index.md
    - HMI-Design:
      - computer-engineering/hmi-design/index.md
    - Digital-Logic:
      - computer-engineering/digital-logic/index.md
    - Electronic-Engineering:
      - computer-engineering/electronic-engineering/index.md
    - VLSI-Design:
      - computer-engineering/vlsi-design/index.md
    

  # Software-Engineering Topic
  - Software-Engineering:
    - software-engineering/index.md
    - Programming:
      - software-engineering/programming/index.md
      - Preparation:
        - software-engineering/programming/preparation/ranking-analysis.md
        - software-engineering/programming/preparation/encoding.md
        - software-engineering/programming/preparation/interfaces.md
      - Basic Tools:
        - software-engineering/programming/basic-tools/editor-ide.md
        - software-engineering/programming/basic-tools/git.md
      - Essentials:
        - software-engineering/programming/essentials/python.md
        - software-engineering/programming/essentials/javascript.md
        - software-engineering/programming/essentials/c.md
        - software-engineering/programming/essentials/go.md
      - Ultimate:
        - software-engineering/programming/ultimate/rust.md
        - software-engineering/programming/ultimate/cpp.md
      - Optional:
        - software-engineering/programming/optional/index.md
        - software-engineering/programming/optional/java.md
        - software-engineering/programming/optional/c-sharp.md
        - Platform-Native:
          - software-engineering/programming/optional/platform-native/swift.md
          - software-engineering/programming/optional/platform-native/kotlin.md
        - Web-First:
          - software-engineering/programming/optional/web-first/ruby.md
          - software-engineering/programming/optional/web-first/php.md
          - software-engineering/programming/optional/web-first/typescript.md
        - Hacker-Toolkit:
          - software-engineering/programming/optional/hacker-toolkit/lua.md
          - software-engineering/programming/optional/hacker-toolkit/perl.md
          - software-engineering/programming/optional/hacker-toolkit/assembly.md
        - Paradigm-Shifters:
          - software-engineering/programming/optional/paradigm-shifters/haskell.md
          - software-engineering/programming/optional/paradigm-shifters/scala.md
          - software-engineering/programming/optional/paradigm-shifters/elixir.md
          - software-engineering/programming/optional/paradigm-shifters/ocaml.md
      - Best Practices:
        - software-engineering/programming/best-practices/index.md
        - software-engineering/programming/design-patterns.md
        - software-engineering/programming/best-practices/coding-style.md
        - software-engineering/programming/best-practices/code-documentation.md
        - software-engineering/programming/best-practices/version-control.md
        - software-engineering/programming/best-practices/testing.md
        - software-engineering/programming/best-practices/code-optimization.md
      - software-engineering/programming/vibe-coding.md

    - Sysadmin:
        - software-engineering/sysadmin/index.md
        - Basic Tools:
          - software-engineering/sysadmin/basic-tools/terminal.md
          - software-engineering/sysadmin/basic-tools/ssh.md
        - GNU/Linux:
          - software-engineering/sysadmin/gnu-linux/index.md
          - software-engineering/sysadmin/gnu-linux/debian.md
          - software-engineering/sysadmin/gnu-linux/rhel.md
          - software-engineering/sysadmin/gnu-linux/suse.md
          - software-engineering/sysadmin/gnu-linux/arch.md
          - software-engineering/sysadmin/gnu-linux/alpine.md
        - Windows:
          - software-engineering/sysadmin/windows/index.md
          - software-engineering/sysadmin/windows/windows-server.md
          - software-engineering/sysadmin/windows/windows-iot.md
        - Container:
          - software-engineering/sysadmin/container/index.md
          - software-engineering/sysadmin/container/docker.md
          - software-engineering/sysadmin/container/k8s.md
        - Virtualization:
          - software-engineering/sysadmin/virtualization/index.md
          - software-engineering/sysadmin/virtualization/kvm.md
          - software-engineering/sysadmin/virtualization/qemu.md
        - software-engineering/sysadmin/android.md
        - software-engineering/sysadmin/freebsd.md
        - software-engineering/sysadmin/darwin-xun.md

    - Databases:
      - software-engineering/databases/index.md
      - RDBMS:
        - software-engineering/databases/rdbms/index.md
        - software-engineering/databases/rdbms/postgresql.md
        - software-engineering/databases/rdbms/sqlite.md
        - software-engineering/databases/rdbms/mysql.md
        - software-engineering/databases/rdbms/oracle.md
        - software-engineering/databases/rdbms/sql-server.md
      - Key-Value:
        - software-engineering/databases/key-value/index.md
      - Document:
        - software-engineering/databases/document/index.md
      - Search-Engine:
        - software-engineering/databases/search-engine/index.md
      - Time-Series:
        - software-engineering/databases/time-series/index.md
      - Column-Family:
        - software-engineering/databases/column-family/index.md
      - Graph:
        - software-engineering/databases/graph/index.md
      

    - Testing:
      - software-engineering/testing/index.md
      # - Unit-Testing:
      #   - software-engineering/testing/unit-testing/index.md
      # - Integration-Testing:
      #   - software-engineering/testing/integration-testing/index.md
      # - End-to-End-Testing:
      #   - software-engineering/testing/end-to-end-testing/index.md
      # - Performance-Testing:
      #   - software-engineering/testing/performance-testing/index.md
      # - Security-Testing:
      #   - software-engineering/testing/security-testing/index.md
      
  # Internet-System Topic
  - Internet-System: 
    - internet-system/index.md
    - Application:
      - internet-system/application/index.md
      - Protocols:
        - internet-system/application/protocols/index.md
        - internet-system/application/protocols/http-https.md
        - internet-system/application/protocols/dns.md
        - internet-system/application/protocols/websockets.md
      - internet-system/application/api.md
      - internet-system/application/architecture.md
      - internet-system/application/application-client.md
      - internet-system/application/application-server.md
      - internet-system/application/use-cases.md
    
    - Network-Engineering:
      - internet-system/network-engineering/index.md

    - Infrastructure:
      - internet-system/infrastructure/index.md
      - Cloud-Platforms:
        - internet-system/infrastructure/cloud-platforms/index.md
        - internet-system/infrastructure/cloud-platforms/public-cloud.md
        - internet-system/infrastructure/cloud-platforms/private-cloud.md
        - internet-system/infrastructure/cloud-platforms/hybrid-cloud.md
        - internet-system/infrastructure/cloud-platforms/edge-computing.md
        - internet-system/infrastructure/storage/object-storage.md
      - internet-system/infrastructure/index.md
      - DevOps:
        - internet-system/infrastructure/devops/index.md
        - internet-system/infrastructure/devops/cicd.md
        - internet-system/infrastructure/devops/configuration.md
        - internet-system/infrastructure/devops/environment.md
        - internet-system/infrastructure/devops/iac.md
        - internet-system/infrastructure/devops/gitops.md
        - internet-system/infrastructure/devops/monitoring.md
        - internet-system/infrastructure/devops/observability.md
        - internet-system/infrastructure/deployment-strategies.md
      - Observability:
        - internet-system/infrastructure/observability/index.md
      - SRE:
        - internet-system/infrastructure/sre/index.md
      - Platform-Engineering:
        - internet-system/infrastructure/platform-engineering/index.md
      - Endpoint-Devices:
        - internet-system/infrastructure/endpoint-devices/index.md

    - IoT:
        - internet-system/iot/index.md

  # Distributed-Systems
  - Data-System:
    - data-systems/index.md


  # Cybersecurity Topic
  - Cybersecurity:
    - cybersecurity/index.md
    - Essential Skills:
      - cybersecurity/essential-skills/index.md
      - Cryptography:
        - cybersecurity/essential-skills/cryptography/index.md
        - cybersecurity/essential-skills/cryptography/cryptographic-attack.md
      - IAM:
        - cybersecurity/essential-skills/iam/index.md
      - Application Security:
        - cybersecurity/essential-skills/application-security/index.md
      - Network Security:
        - cybersecurity/essential-skills/network-security/index.md
      - Reverse Engineering:
        - cybersecurity/essential-skills/reverse-engineering/index.md
      - Binary Security:
        - cybersecurity/essential-skills/binary-security/index.md

    - Platforms Security:
      - cybersecurity/platforms-security/index.md
      - Cloud Security:
        - cybersecurity/platforms-security/application-security/index.md
      - Endpoint Security:
        - cybersecurity/platforms-security/endpoint-security/index.md
      - IoT Security:
        - cybersecurity/platforms-security/application-security/index.md
      - Mobile Security:
        - cybersecurity/platforms-security/application-security/index.md
    
    - CTF:
      - cybersecurity/ctf/index.md
      # - cybersecurity/ctf/crypto.md
      # - cybersecurity/ctf/misc.md
      # - cybersecurity/ctf/web.md
      # - cybersecurity/ctf/reverse.md
      # - cybersecurity/ctf/pwn.md

    - Offensive Security:
      - cybersecurity/offensive-security/index.md
      # - cybersecurity/offensive-security/penetration-testing.md
      # - cybersecurity/offensive-security/red-teaming.md
    - Defensive Security:
      - cybersecurity/defensive-security/index.md
      # - cybersecurity/defensive-security/blue-teaming.md
      # - cybersecurity/defensive-security/incident-response.md
      # - cybersecurity/defensive-security/threat-hunting.md
      # - cybersecurity/defensive-security/digital-forensics.md
      
    - Vulnerability Databases:
      - cybersecurity/vulnerability-databases/index.md

    - Data Security & Privacy:
      - cybersecurity/data-security/index.md
      # - Data Privacy:
      #   - cybersecurity/security-core/data-privacy/index.md
      # - Data Protection:
      #   - cybersecurity/security-core/data-protection/index.md
      # - Data Integrity:
      #   - cybersecurity/security-core/data-integrity/index.md
      # - Data Availability:
      #   - cybersecurity/security-core/data-availability/index.md
      # - GRC:
      #   - cybersecurity/security-core/grc/index.md


  # Explore-AI Topic
  - Explore-AI:
    - explore-ai/index.md

  # Interesting Topic
  - Interesting-Practice:
    # - interesting-practice/index.md
    - HomeLab:
      - interesting-practice/homelab/index.md
    - CyberDeck:
      - interesting-practice/cyberdeck/index.md

plugins:
  - search
  - macros

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true 

extra:
  files_server: "https://files.cyberspace.bar"
  # files_server: "https://files.cyberspace.bar/cyberspace-explore"

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js 
