# Project information
site_name: Cyberspace Explore 
use_directory_urls: true

# Repository
# repo_name: Cyberspace-Explore
# repo_url: https://github.com/AvenMay/cyberspace-explore

# Configuration
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/rocket-launch
    # repo: fontawesome/brands/github
  palette:
    - scheme: default    # 浅色模式
      # primary: indigo
      # accent: indigo
      primary: blue
      accent: pink
      toggle:
        icon: material/weather-night
        name: 切换到深色模式
    - scheme: slate      # 深色模式
      # primary: indigo
      # accent: indigo
      primary: blue
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono

  toc:
    on_page: true
    depth: 5


# Page tree
nav:
  - Home: index.md

  # Computer-Science Topic
  - Computer-Science: 
    - computer-science/index.md
    - Programming Languages:
      - computer-science/programming-languages/index.md
      - Compilers:
        - computer-science/programming-languages/compilers/index.md

    - Algorithms & Data-Structures:
      - computer-science/algorithms-data-structures/index.md
      - computer-science/algorithms-data-structures/foundation.md
      - computer-science/algorithms-data-structures/advanced.md
      - computer-science/algorithms-data-structures/problem-solving-techniques.md
    - Computer Architecture:
      - computer-science/computer-architecture/index.md
    - Operating System: 
      - computer-science/operating-system/index.md
      - Unix-like:
        - computer-science/operating-system/unix-and-unix-like/index.md
        - computer-science/operating-system/unix-and-unix-like/linux.md
        - computer-science/operating-system/unix-and-unix-like/bsd.md
        - computer-science/operating-system/unix-and-unix-like/xnu.md
        - computer-science/operating-system/unix-and-unix-like/android.md
      - computer-science/operating-system/windows-nt.md
      - Teaching Purposes:
        - computer-science/operating-system/teaching-purposes/xv6.md
        - computer-science/operating-system/teaching-purposes/pintos.md
        - computer-science/operating-system/teaching-purposes/nachos.md
        - computer-science/operating-system/teaching-purposes/minix3.md
      - Special Use-Cases:
        - computer-science/operating-system/special-use-cases/virtualization.md
        - computer-science/operating-system/special-use-cases/containerization.md
        - computer-science/operating-system/special-use-cases/real-time-os.md
      - computer-science/operating-system/boot-process.md
      - computer-science/operating-system/experimental-os.md

    - Computer Networking:
      - computer-science/computer-networking/index.md
    - Mathematics:
      - computer-science/mathematics/index.md
    - Databases Systems:
      - computer-science/databases-systems/index.md
    - Distributed Systems:
      - computer-science/distributed-systems/index.md
    - Computer Graphics:
      - computer-science/computer-graphics/index.md

  # Software-Engineering Topic
  - Software-Engineering:
    - software-engineering/index.md
    - Programming:
      - software-engineering/programming/index.md
      - Preparation:
        - software-engineering/programming/preparation/ranking-analysis.md
        - software-engineering/programming/preparation/encoding.md
      # - Design Patterns:
      - software-engineering/programming/design-patterns.md
        # - software-engineering/programming/design-patterns/creational.md
        # - software-engineering/programming/design-patterns/structural.md
        # - software-engineering/programming/design-patterns/behavioral.md
      - software-engineering/programming/interfaces.md
      - Dynamic:
        - software-engineering/programming/dynamic/python.md
        - software-engineering/programming/dynamic/javascript.md
        - software-engineering/programming/dynamic/ruby.md
        - software-engineering/programming/dynamic/php.md
        - software-engineering/programming/dynamic/lua.md
        - software-engineering/programming/dynamic/perl.md
      - Static:
        - software-engineering/programming/static/go.md
        - software-engineering/programming/static/typescript.md
        - software-engineering/programming/static/java.md
        - software-engineering/programming/static/c-sharp.md
        - software-engineering/programming/static/kotlin.md
        - software-engineering/programming/static/swift.md
      - System-Level:
        - software-engineering/programming/system-level/c.md
        - software-engineering/programming/system-level/cpp.md
        - software-engineering/programming/system-level/rust.md
        - software-engineering/programming/system-level/assembly.md
      - Functional:
        - software-engineering/programming/functional/haskell.md
        - software-engineering/programming/functional/scala.md
        - software-engineering/programming/functional/ocaml.md
        - software-engineering/programming/functional/elixir.md

    - Development:
      - software-engineering/development/index.md
      - software-engineering/development/editor-ide.md
      - software-engineering/development/vibe-coding.md
      - software-engineering/development/devops.md
      - software-engineering/development/git.md
      - software-engineering/development/cicd.md
      - software-engineering/development/testing.md
    - Operations:
      - software-engineering/operations/index.md
      - Sysadmin:
        - software-engineering/operations/sysadmin/index.md
        - software-engineering/operations/sysadmin/unix-linux.md
        - software-engineering/operations/sysadmin/windows.md
      - software-engineering/operations/deployment.md
      - Infrastructure Management:
        - software-engineering/operations//infrastructure-management/configuration.md
        - software-engineering/operations//infrastructure-management/environment.md
        - software-engineering/operations/infrastructure-management/iac.md
        - software-engineering/operations/infrastructure-management/gitops.md
        - software-engineering/operations/infrastructure-management/monitoring.md
        - software-engineering/operations/infrastructure-management/observability.md
      - software-engineering/operations/sre.md
      - software-engineering/operations/platform-engineering.md
    - Collaboration:
      - software-engineering/collaboration/index.md

  # Computer-Engineering Topic
  - Computer-Engineering:
    - computer-engineering/index.md
    - Embedded-System:
      - computer-engineering/embedded-system/index.md
    - 3D-Printing:
      - computer-engineering/3d-printing/index.md
    - HMI-Design:
      - computer-engineering/hmi-design/index.md
    - Digital-Logic:
      - computer-engineering/digital-logic/index.md
    - Electronic-Engineering:
      - computer-engineering/electronic-engineering/index.md
    - VLSI-Design:
      - computer-engineering/vlsi-design/index.md
    

  # Internet-System Topic
  - Internet-System: 
    - internet-system/index.md
    - System-Design:
      - internet-system/system-design/index.md
    - Application:
      - internet-system/application/index.md
      - Protocols:
        - internet-system/application/protocols/index.md
        - internet-system/application/protocols/http-https.md
        - internet-system/application/protocols/dns.md
        - internet-system/application/protocols/websockets.md
        - internet-system/application/protocols/ssh.md
        # - internet-system/application/protocols/ftp.md
        # - internet-system/application/protocols/smtp.md
      - internet-system/application/api.md
      - internet-system/application/architecture.md
      - internet-system/application/application-client.md
      - internet-system/application/application-server.md
      - internet-system/application/middleware.md
      - internet-system/application/databases.md
      - internet-system/application/use-cases.md
    - Infrastructure:
      - internet-system/infrastructure/index.md
      - Network-Engineering:
        - internet-system/infrastructure/network-engineering/index.md
      - Compute:
        - internet-system/infrastructure/compute/index.md
        - internet-system/infrastructure/compute/operating-systems.md
        - internet-system/infrastructure/compute/virtualization.md
        - internet-system/infrastructure/compute/containerization.md
      - Storage:
        - internet-system/infrastructure/storage/index.md
        - internet-system/infrastructure/storage/block-storage.md
        - internet-system/infrastructure/storage/file-storage.md
        - internet-system/infrastructure/storage/object-storage.md
      - Cloud-Platforms:
        - internet-system/infrastructure/cloud-platforms/index.md
        - internet-system/infrastructure/cloud-platforms/public-cloud.md
        - internet-system/infrastructure/cloud-platforms/private-cloud.md
        - internet-system/infrastructure/cloud-platforms/hybrid-cloud.md
        - internet-system/infrastructure/cloud-platforms/edge-computing.md
      - Client-Devices:
        - internet-system/infrastructure/client-devices/index.md

    - IoT:
        - internet-system/iot/index.md

  # Cybersecurity Topic
  - Cybersecurity:
    - cybersecurity/index.md
    - Cryptography:
      - cybersecurity/cryptography/index.md
    - Security-Skills:
      - cybersecurity/security-skills/index.md
    - Security-Topics:
      - cybersecurity/security-topics/index.md
    - CTF:
      - cybersecurity/ctf/index.md
    - Offensive-Security:
      - cybersecurity/offensive-security/index.md
    - Defensive-Security:
      - cybersecurity/defensive-security/index.md

  # Artificial-Intelligence Topic
  - Artificial-Intelligence:
    - artificial-intelligence/index.md

  # Interesting Topic
  - Interesting-Practice:
    # - interesting-practice/index.md
    - HomeLab:
      - interesting-practice/homelab/index.md
    - CyberDeck:
      - interesting-practice/cyberdeck/index.md

plugins:
  - search
  - macros

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true 

extra:
  files_server: "https://files.cyberspace.bar"
  # files_server: "https://files.cyberspace.bar/cyberspace-explore"

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js 
